### ISSUE TITLE
 No module named 'onnx2tflite.components'

### ISSUE THREAD

**Issue by Joke66** [MPolaris/onnx2tflite#86]
from onnx2tflite import onnx_converter
  File "/usr/local/lib/python3.10/dist-packages/onnx2tflite-2.0-py3.10.egg/onnx2tflite/__init__.py", line 3, in <module>
  File "/usr/local/lib/python3.10/dist-packages/onnx2tflite-2.0-py3.10.egg/onnx2tflite/converter.py", line 3, in <module>
ModuleNotFoundError: No module named 'onnx2tflite.components'

**Comment by MPolaris** [comment]
ensure you have install `onnx2tflite` according to 'Install' tag.

**Comment by yrik** [comment]
what do you mean? I have the same problem

**Comment by Ludwig-Work** [comment]
I just came across this problem too, while installing it using `pip install ./onnx2tflite` (because manually invoking a `setup.py` is [generally advised against](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html)).
Here's a fix: Go to `onnx2tflite/setup.py` and replace `packages=find_packages(include=['onnx2tflite']),` with `packages=find_packages(where=abs_path),` to install all sub-packages and not only the main package.
After this edit, installing with pip works fine for me.

(Edit: Or refer to #93)

**Comment by lopezemi** [comment]
> I just came across this problem too, while installing it using `pip install ./onnx2tflite` (because manually invoking a `setup.py` is [generally advised against](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html)). Here's a fix: Go to `onnx2tflite/setup.py` and replace `packages=find_packages(include=['onnx2tflite']),` with `packages=find_packages(where=abs_path),` to install all sub-packages and not only the main package. After this edit, installing with pip works fine for me.
> 
> (Edit: Or refer to [#93](https://github.com/MPolaris/onnx2tflite/pull/93))

I can confirm this worked for me too. I no longer have this import error.
